from tkinter import *
main=Tk()
main.geometry("1920x1080")
main.config(bg="black")
main.title("Matrix Inverse Founder")
def mi2x2():
    mi=Tk()
    mi.config(bg="black")
    mi.title("Matrix Inverse Founder")
    mi.geometry("1920x1080")
    Label(mi,text="2x2 Matrix Inverse",bg="black",fg="white",font="mono 50 bold underline").pack()
    c1=Canvas(mi,width=9,height=320,bg="white").place(x=1200,y=100)
    c2=Canvas(mi,width=9,height=320,bg="white").place(x=750,y=100)
    c3=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=100)
    c4=Canvas(mi,width=50,height=9,bg="white").place(x=1150,y=100)
    c5=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=420)
    c5=Canvas(mi,width=59,height=9,bg="white").place(x=1150,y=420)
    a=Entry(mi,width=5,font="arial 40",bg="yellow",fg="black")
    a.place(x=800,y=150)
    b=Entry(mi,width=5,font="arial 40",bg="yellow",fg="black")
    b.place(x=1000,y=150)
    c=Entry(mi,width=5,font="arial 40",bg="yellow",fg="black")
    c.place(x=800,y=300)
    d=Entry(mi,width=5,font="arial 40",bg="yellow",fg="black")
    d.place(x=1000,y=300)
    def mip():
        try:
            ans=int((int(a.get())*int(d.get()))-(int(b.get())*int(c.get())))
            if ans!=0:
                c1=Canvas(mi,width=9,height=320,bg="white").place(x=1200,y=600)
                c2=Canvas(mi,width=9,height=320,bg="white").place(x=750,y=600)
                c3=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=600)
                c4=Canvas(mi,width=50,height=9,bg="white").place(x=1150,y=600)
                c5=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=920)
                c5=Canvas(mi,width=59,height=9,bg="white").place(x=1150,y=920)
                if ans<0:
                    ans=-(ans)
                    Label(mi,text=str(-int(d.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=800,y=650)
                    Label(mi,text=str(int(b.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=1000,y=650)
                    Label(mi,text=str(int(c.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=800,y=800)
                    Label(mi,text=str(-int(a.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=1000,y=800)
                else:
                    Label(mi,text=str(int(d.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=800,y=650)
                    Label(mi,text=str(-int(b.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=1000,y=650)
                    Label(mi,text=str(-int(c.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=800,y=800)
                    Label(mi,text=str(int(a.get()))+"/"+str(ans),width=5,font="arial 40",bg="yellow",fg="black").place(x=1000,y=800)
        except:
            pass    
    Button(mi,text="Answer",command=mip,bg="maroon",fg="white",font="arial 40").place(x=880,y=500)
    mi.mainloop()
def mi3x3():
    mi=Tk()
    mi.config(bg="black")
    mi.title("Matrix Inverse Founder")
    mi.geometry("1920x1080")
    Label(mi,text="3x3 Matrix Inverse",bg="black",fg="white",font="mono 50 bold underline").pack()
    c1=Canvas(mi,width=9,height=320,bg="white").place(x=1200,y=100)
    c2=Canvas(mi,width=9,height=320,bg="white").place(x=750,y=100)
    c3=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=100)
    c4=Canvas(mi,width=50,height=9,bg="white").place(x=1150,y=100)
    c5=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=420)
    c6=Canvas(mi,width=59,height=9,bg="white").place(x=1150,y=420)
    a=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    a.place(x=780,y=150)
    b=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    b.place(x=925,y=150)
    c=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    c.place(x=1070,y=150)
    d=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    d.place(x=780,y=250)
    e=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    e.place(x=925,y=250)
    f=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    f.place(x=1070,y=250)
    g=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    g.place(x=780,y=350)
    h=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    h.place(x=925,y=350)
    i=Entry(mi,width=5,font="arial 30",bg="yellow",fg="black")
    i.place(x=1070,y=350)
    
        
    def mip():
        try:
            
            co1=(int(e.get())*int(i.get()))-(int(f.get())*int(h.get()))           
            co3=(int(d.get())*int(h.get()))-(int(e.get())*int(g.get()))           
            co2=(int(d.get())*int(i.get()))-(int(f.get())*int(g.get()))           
            ans=int(int(a.get())*co1-int(b.get())*co2+int(c.get())*co3)
            if ans!=0:
                        
                A=(((int(e.get())*int(i.get()))-(int(f.get())*int(h.get()))))
                B=(((int(d.get())*int(i.get()))-(int(f.get())*int(g.get())))*-1)
                C=(((int(d.get())*int(h.get()))-(int(e.get())*int(g.get()))))
                D=(((int(b.get())*int(i.get()))-(int(h.get())*int(c.get())))*-1)
                E=(((int(a.get())*int(i.get()))-(int(c.get())*int(g.get()))))
                F=(((int(a.get())*int(h.get()))-(int(b.get())*int(g.get())))*-1)
                G=(((int(b.get())*int(f.get()))-(int(e.get())*int(c.get()))))
                H=(((int(a.get())*int(f.get()))-(int(d.get())*int(c.get())))*-1)
                I=(((int(a.get())*int(e.get()))-(int(d.get())*int(b.get()))))
                
                if ans<0:
                    ans=-(ans)
                    Label(mi,text=str(-(int(A)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=780,y=650)
                    Label(mi,text=str(-(int(D)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=925,y=650)
                    Label(mi,text=str(-(int(G)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=1070,y=650)
                    Label(mi,text=str(-(int(B)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=780,y=750)
                    Label(mi,text=str(-(int(E)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=925,y=750)
                    Label(mi,text=str(-(int(H)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=1070,y=750)
                    Label(mi,text=str(-(int(C)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=780,y=850)
                    Label(mi,text=str(-(int(F)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=925,y=850)
                    Label(mi,text=str(-(int(I)))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=1070,y=850)

                else :
                    Label(mi,text=str(int(A))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=780,y=650)
                    Label(mi,text=str(int(D))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=925,y=650)
                    Label(mi,text=str(int(G))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=1070,y=650)
                    Label(mi,text=str(int(B))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=780,y=750)
                    Label(mi,text=str(int(E))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=925,y=750)
                    Label(mi,text=str(int(H))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=1070,y=750)
                    Label(mi,text=str(int(C))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=780,y=850)
                    Label(mi,text=str(int(F))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=925,y=850)
                    Label(mi,text=str(int(I))+"/"+str(ans),width=5,font="arial 30",bg="yellow",fg="black").place(x=1070,y=850)
                                
                
                c1=Canvas(mi,width=9,height=320,bg="white").place(x=1200,y=600)
                c2=Canvas(mi,width=9,height=320,bg="white").place(x=750,y=600)
                c3=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=600)
                c4=Canvas(mi,width=50,height=9,bg="white").place(x=1150,y=600)
                c5=Canvas(mi,width=60,height=9,bg="white").place(x=750,y=920)
                c6=Canvas(mi,width=59,height=9,bg="white").place(x=1150,y=920)                               
                
        except:
            pass
    Button(mi,text="Answer",command=mip,bg="maroon",fg="white",font="arial 40").place(x=880,y=450)
    mi.mainloop()
Label(main,text="Matrix Inverse Founder\n\n",bg="black",fg="white",font="mono 50 bold underline").pack()
Button(main,text="2x2 Matrix",command=mi2x2,bg="maroon",fg="white",font="arial 40").pack()
Label(main,text="\n",bg="black").pack()
Button(main,text="3x3 Matrix",command=mi3x3,bg="maroon",fg="white",font="arial 40").pack()
main.mainloop()
